const PREREQUISITES = {
  "CS": {
    "CS1002": { name: "Programming Fundamentals", credits: 3, prereqs: [], postreqs: ["CS1004"] },
    "CS1004": { name: "Object Oriented Programming", credits: 3, prereqs: ["CS1002"], postreqs: ["CS2001", "EE3002"] },
    "MT1003": { name: "Calculus and Analytical Geometry", credits: 3, prereqs: [], postreqs: ["MT2008", "MT1006"] },
    "EE1005": { name: "Digital Logic Design", credits: 3, prereqs: [], postreqs: ["EE2003"] },
    "MT2008": { name: "Multivariable Calculus", credits: 3, prereqs: ["MT1003"], postreqs: [] },
    "MT1006": { name: "Multivariable Calculus", credits: 3, prereqs: ["MT1003"], postreqs: [] },
    "EE2003": { name: "Computer Organization and Assembly Language", credits: 3, prereqs: ["EE1005"], postreqs: ["EE3009"] },
    "CS2001": { name: "Data Structures", credits: 3, prereqs: ["CS1004"], postreqs: ["CS2005", "CS2006", "CS2009", "CS3001", "CS3006"] },
    "CS2005": { name: "Database Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS2006": { name: "Operating Systems", credits: 3, prereqs: ["CS2001"], postreqs: ["CS3006"] },
    "CS2009": { name: "Design and Analysis of Algorithms", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "AI2002": { name: "Artificial Intelligence", credits: 3, prereqs: [], postreqs: [] },
    "CS3001": { name: "Computer Networks", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS3006": { name: "Parallel and Distributed Computing", credits: 3, prereqs: ["CS2006"], postreqs: [] },
    "EE3009": { name: "Computer Architecture", credits: 3, prereqs: ["EE2003"], postreqs: [] },
    "CS3005": { name: "Theory of Automata", credits: 3, prereqs: [], postreqs: ["CS4031"] },
    "CS4031": { name: "Compiler Construction", credits: 3, prereqs: ["CS3005"], postreqs: [] },
    "CS3014": { name: "Applied Human Computer Interaction", credits: 3, prereqs: [], postreqs: [] },
    "CS3009": { name: "Software Engineering", credits: 3, prereqs: [], postreqs: [] },
    "CS4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["CS4092"] },
    "CS4092": { name: "Final Year Project - II", credits: 0, prereqs: ["CS4091"], postreqs: [] },
    "CS3002": { name: "Information Security", credits: 3, prereqs: [], postreqs: [] },
    "CS4001": { name: "Professional Practices in IT", credits: 3, prereqs: [], postreqs: [] },
    "CS4087": { name: "Advanced DBMS", credits: 3, prereqs: ["CS2005"], postreqs: [] },
    "SS1014": { name: "Expository Writing", credits: 2, prereqs: [], postreqs: ["SS2007"] },
    "SS2007": { name: "Technical and Business Writing", credits: 3, prereqs: ["SS1014"], postreqs: [] }
  },
  "AI": {
    "CS1002": { name: "Programming Fundamentals", credits: 3, prereqs: [], postreqs: ["CS1004"] },
    "CS1004": { name: "Object Oriented Programming", credits: 3, prereqs: ["CS1002"], postreqs: ["CS2001"] },
    "MT1003": { name: "Calculus and Analytical Geometry", credits: 3, prereqs: [], postreqs: ["MT2008"] },
    "EE1005": { name: "Digital Logic Design", credits: 3, prereqs: [], postreqs: ["EE2003"] },
    "MT2008": { name: "Multivariable Calculus", credits: 3, prereqs: ["MT1003"], postreqs: [] },
    "EE2003": { name: "Computer Organization and Assembly Language", credits: 3, prereqs: ["EE1005"], postreqs: [] },
    "CS2001": { name: "Data Structures", credits: 3, prereqs: ["CS1004"], postreqs: ["CS2005", "CS2006", "CS2009"] },
    "CS2005": { name: "Database Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS2006": { name: "Operating Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "AI2001": { name: "Programming for AI", credits: 3, prereqs: [], postreqs: ["AI3002", "AI3003"] },
    "AI2002": { name: "Artificial Intelligence", credits: 3, prereqs: [], postreqs: [] },
    "AI3001": { name: "Knowledge Representation and Reasoning", credits: 3, prereqs: ["AI2001"], postreqs: [] },
    "AI3002": { name: "Machine Learning", credits: 3, prereqs: ["AI2001"], postreqs: ["AI4002"] },
    "AI3003": { name: "Artificial Neural Networks", credits: 3, prereqs: ["AI2001"], postreqs: [] },
    "AI4002": { name: "Computer Vision", credits: 3, prereqs: ["AI3002"], postreqs: [] },
    "CS3001": { name: "Computer Networks", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "AI4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["AI4092"] },
    "AI4092": { name: "Final Year Project - II", credits: 0, prereqs: ["AI4091"], postreqs: [] }
  },
  "SE": {
    "CS1002": { name: "Programming Fundamentals", credits: 3, prereqs: [], postreqs: ["CS1004"] },
    "CS1004": { name: "Object Oriented Programming", credits: 3, prereqs: ["CS1002"], postreqs: ["CS2001", "SE2002"] },
    "MT1003": { name: "Calculus and Analytical Geometry", credits: 3, prereqs: [], postreqs: ["MT1006"] },
    "EE1005": { name: "Digital Logic Design", credits: 3, prereqs: [], postreqs: ["EE2003"] },
    "MT1006": { name: "Multivariable Calculus", credits: 3, prereqs: ["MT1003"], postreqs: [] },
    "EE2003": { name: "Computer Organization and Assembly Language", credits: 3, prereqs: ["EE1005"], postreqs: [] },
    "CS2001": { name: "Data Structures", credits: 3, prereqs: ["CS1004"], postreqs: ["CS2005", "CS2006", "CS2009"] },
    "SE1001": { name: "Introduction to Software Engineering", credits: 3, prereqs: [], postreqs: ["SE2001", "SE3002"] },
    "SE2001": { name: "Software Requirements Engineering", credits: 3, prereqs: ["SE1001"], postreqs: [] },
    "SE2002": { name: "Software Design and Architecture", credits: 3, prereqs: ["CS1004"], postreqs: ["SE3004"] },
    "SE3002": { name: "Software Quality Engineering", credits: 3, prereqs: ["SE1001"], postreqs: [] },
    "SE3004": { name: "Software Construction and Development", credits: 3, prereqs: ["SE2002"], postreqs: [] },
    "CS2005": { name: "Database Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS2006": { name: "Operating Systems", credits: 3, prereqs: ["CS2001"], postreqs: ["CS3006"] },
    "AI2002": { name: "Artificial Intelligence", credits: 3, prereqs: [], postreqs: [] },
    "CS2009": { name: "Design and Analysis of Algorithms", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS3001": { name: "Computer Networks", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS3006": { name: "Parallel and Distributed Computing", credits: 3, prereqs: ["CS2006"], postreqs: [] },
    "SE4002": { name: "Fundamentals of Software Project Management", credits: 3, prereqs: ["SE2001"], postreqs: [] },
    "SE4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["SE4092"] },
    "SE4092": { name: "Final Year Project - II", credits: 0, prereqs: ["SE4091"], postreqs: [] },
    "SS1014": { name: "Expository Writing", credits: 2, prereqs: [], postreqs: ["SS2007"] },
    "SS2007": { name: "Technical and Business Writing", credits: 3, prereqs: ["SS1014"], postreqs: [] }
  },
  "DS": {
    "CS1002": { name: "Programming Fundamentals", credits: 3, prereqs: [], postreqs: ["CS1004"] },
    "CS1004": { name: "Object Oriented Programming", credits: 3, prereqs: ["CS1002"], postreqs: ["CS2001"] },
    "MT1003": { name: "Calculus and Analytical Geometry", credits: 3, prereqs: [], postreqs: ["MT2008"] },
    "EE1005": { name: "Digital Logic Design", credits: 3, prereqs: [], postreqs: [] },
    "MT2008": { name: "Multivariable Calculus", credits: 3, prereqs: ["MT1003"], postreqs: [] },
    "CS2001": { name: "Data Structures", credits: 3, prereqs: ["CS1004"], postreqs: ["CS2005", "CS2006", "CS2009"] },
    "DS2001": { name: "Introduction to Data Science", credits: 3, prereqs: [], postreqs: ["DS3001"] },
    "DS2003": { name: "Advanced Statistics", credits: 3, prereqs: [], postreqs: [] },
    "CS2005": { name: "Database Systems", credits: 3, prereqs: ["CS2001"], postreqs: ["DS3003"] },
    "CS2006": { name: "Operating Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "AI2002": { name: "Artificial Intelligence", credits: 3, prereqs: [], postreqs: [] },
    "DS3001": { name: "Data Analysis and Visualization", credits: 3, prereqs: ["DS2001"], postreqs: [] },
    "DS3002": { name: "Data Mining", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "DS3003": { name: "Data Warehousing and Business Intelligence", credits: 3, prereqs: ["CS2005"], postreqs: [] },
    "CS3001": { name: "Computer Networks", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS3006": { name: "Parallel and Distributed Computing", credits: 3, prereqs: ["CS2006"], postreqs: [] },
    "CS3004": { name: "Data Structures Elective", credits: 3, prereqs: ["CS1004"], postreqs: [] },
    "DS4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["DS4092"] },
    "DS4092": { name: "Final Year Project - II", credits: 0, prereqs: ["DS4091"], postreqs: [] },
    "SS1014": { name: "Expository Writing", credits: 2, prereqs: [], postreqs: ["SS2007"] },
    "SS2007": { name: "Technical and Business Writing", credits: 3, prereqs: ["SS1014"], postreqs: [] }
  },
  "CY": {
    "CS1002": { name: "Programming Fundamentals", credits: 3, prereqs: [], postreqs: ["CS1004"] },
    "CS1004": { name: "Object Oriented Programming", credits: 3, prereqs: ["CS1002"], postreqs: ["CS2001"] },
    "MT1003": { name: "Calculus and Analytical Geometry", credits: 3, prereqs: [], postreqs: ["MT2008"] },
    "EE1005": { name: "Digital Logic Design", credits: 3, prereqs: [], postreqs: ["EE2003"] },
    "MT2008": { name: "Multivariable Calculus", credits: 3, prereqs: ["MT1003"], postreqs: [] },
    "EE2003": { name: "Computer Organization and Assembly Language", credits: 3, prereqs: ["EE1005"], postreqs: [] },
    "CS2001": { name: "Data Structures", credits: 3, prereqs: ["CS1004"], postreqs: ["CS2005", "CS2006"] },
    "CS2005": { name: "Database Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS2006": { name: "Operating Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CY2004": { name: "Cyber Security Fundamentals", credits: 3, prereqs: [], postreqs: ["CY3001", "CY3006"] },
    "CS3001": { name: "Computer Networks", credits: 3, prereqs: ["CS2001"], postreqs: ["CY3001"] },
    "CY3001": { name: "Network Security", credits: 3, prereqs: ["CS3001"], postreqs: [] },
    "CY3006": { name: "Digital Forensics", credits: 3, prereqs: ["CY2004"], postreqs: [] },
    "CS3009": { name: "Software Engineering", credits: 3, prereqs: [], postreqs: ["CY4001"] },
    "CY4001": { name: "Secure Software Design and Development", credits: 3, prereqs: ["CS3009"], postreqs: [] },
    "CS3006": { name: "Parallel and Distributed Computing", credits: 3, prereqs: ["CS2006"], postreqs: [] },
    "CY4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["CY4092"] },
    "CY4092": { name: "Final Year Project - II", credits: 0, prereqs: ["CY4091"], postreqs: [] }
  },
  "CE": {
    "CS1009": { name: "Applications of ICT", credits: 2, prereqs: [], postreqs: ["CS1002"] },
    "CS1002": { name: "Programming Fundamentals", credits: 3, prereqs: ["CS1009"], postreqs: ["CS1004"] },
    "CS1004": { name: "Object Oriented Programming", credits: 3, prereqs: ["CS1002"], postreqs: ["CS2002", "EE3002"] },
    "MT1001": { name: "Applied Calculus", credits: 3, prereqs: [], postreqs: ["MT1006"] },
    "MT1006": { name: "Differential Equations", credits: 3, prereqs: ["MT1001"], postreqs: ["MT2003"] },
    "MT1004": { name: "Linear Algebra", credits: 3, prereqs: ["MT1001"], postreqs: [] },
    "MT2003": { name: "Complex Variables and Transforms", credits: 3, prereqs: ["MT1006"], postreqs: ["EE2008"] },
    "EE1001": { name: "Linear Circuit Analysis", credits: 3, prereqs: [], postreqs: ["EE1004", "EE2004"] },
    "EE1004": { name: "Electronic Devices and Circuits", credits: 3, prereqs: ["EE1001"], postreqs: [] },
    "EE2004": { name: "Electrical Network Analysis", credits: 3, prereqs: ["EE1001"], postreqs: [] },
    "EE1002": { name: "Basic Electrical Engineering", credits: 3, prereqs: [], postreqs: ["EE2003"] },
    "EE2003": { name: "Computer Organization and Architecture", credits: 3, prereqs: ["EE1002"], postreqs: ["EE3002"] },
    "EE2008": { name: "Signals and Systems", credits: 3, prereqs: ["MT2003"], postreqs: ["EE3031"] },
    "EE1005": { name: "Digital Logic Design", credits: 3, prereqs: [], postreqs: ["EE3002", "EE3033"] },
    "CS2002": { name: "Data Structures and Algorithms", credits: 3, prereqs: ["CS1002"], postreqs: [] },
    "CS2005": { name: "Database Systems", credits: 3, prereqs: ["CS2001"], postreqs: [] },
    "CS2006": { name: "Operating Systems", credits: 3, prereqs: ["CS2002"], postreqs: [] },
    "EE3002": { name: "Microprocessor Interfacing and Programming", credits: 3, prereqs: ["CS1004", "EE1005"], postreqs: [] },
    "EE3031": { name: "Digital Signal Processing", credits: 3, prereqs: ["EE2008"], postreqs: [] },
    "EE3033": { name: "Digital Design", credits: 3, prereqs: ["EE1005"], postreqs: [] },
    "EE2007": { name: "Data Communication and Networks", credits: 3, prereqs: [], postreqs: [] },
    "EE4091": { name: "Final Year Project - I", credits: 3, prereqs: [], postreqs: ["EE4092"] },
    "EE4092": { name: "Final Year Project - II", credits: 3, prereqs: ["EE4091"], postreqs: [] }
  },
  "EE": {
    "CS1009": { name: "Applications of ICT", credits: 2, prereqs: [], postreqs: ["CS1011"] },
    "CS1011": { name: "Programming for Engineers", credits: 3, prereqs: ["CS1009"], postreqs: ["CS2021"] },
    "MT1001": { name: "Applied Calculus", credits: 3, prereqs: [], postreqs: ["MT1006", "MT1004"] },
    "MT1006": { name: "Differential Equations", credits: 3, prereqs: ["MT1001"], postreqs: ["MT2003", "MT2008"] },
    "MT1004": { name: "Linear Algebra", credits: 3, prereqs: ["MT1001"], postreqs: [] },
    "MT2003": { name: "Complex Variables and Transforms", credits: 3, prereqs: ["MT1006"], postreqs: ["EE3005"] },
    "MT2008": { name: "Multivariable Calculus", credits: 3, prereqs: ["MT1006"], postreqs: [] },
    "EE1001": { name: "Linear Circuit Analysis", credits: 3, prereqs: [], postreqs: ["EE1004", "EE2004"] },
    "EE1004": { name: "Electronic Devices and Circuits", credits: 3, prereqs: ["EE1001"], postreqs: ["EE3003"] },
    "EE2004": { name: "Electrical Network Analysis", credits: 3, prereqs: ["EE1001"], postreqs: [] },
    "EE1005": { name: "Digital Logic Design", credits: 3, prereqs: [], postreqs: ["EE3002"] },
    "CS2021": { name: "Object Oriented Data Structures", credits: 3, prereqs: ["CS1011"], postreqs: [] },
    "EE2008": { name: "Signals and Systems", credits: 3, prereqs: ["MT2003"], postreqs: ["EE3004", "EE3003", "EE3005"] },
    "EE2010": { name: "Electro-Mechanical Systems", credits: 3, prereqs: ["NS1002", "EE2004"], postreqs: [] },
    "EE2011": { name: "Instrumentation and Measurement", credits: 3, prereqs: ["EE2008"], postreqs: [] },
    "EE3002": { name: "Microprocessor Interfacing and Programming", credits: 3, prereqs: ["CS1004", "EE1005"], postreqs: [] },
    "EE3003": { name: "Analogue and Digital Communication", credits: 3, prereqs: ["EE2011", "EE2008"], postreqs: [] },
    "EE3004": { name: "Feedback Control Systems", credits: 3, prereqs: ["EE2008"], postreqs: [] },
    "EE3005": { name: "Electromagnetic Theory", credits: 3, prereqs: ["MT2008"], postreqs: [] },
    "EE2038": { name: "Power Distribution and Utilization", credits: 3, prereqs: [], postreqs: [] },
    "EE4091": { name: "Final Year Project - I", credits: 3, prereqs: [], postreqs: ["EE4092"] },
    "EE4092": { name: "Final Year Project - II", credits: 0, prereqs: ["EE4091"], postreqs: [] }
  },
  "CV": {
    "CV1001": { name: "Civil Engineering Materials", credits: 2, prereqs: [], postreqs: [] },
    "CV1002": { name: "Engineering Drawing", credits: 1, prereqs: [], postreqs: ["CV2009"] },
    "CV1003": { name: "Engineering Surveying", credits: 2, prereqs: [], postreqs: ["CV2001"] },
    "MT2007": { name: "Numerical Analysis", credits: 3, prereqs: [], postreqs: [] },
    "CV2001": { name: "Advanced Engineering Surveying", credits: 2, prereqs: ["CV1003"], postreqs: [] },
    "CV2002": { name: "Fluid Mechanics", credits: 2, prereqs: [], postreqs: ["CV3001", "CV4009"] },
    "CV2003": { name: "Soil Mechanics", credits: 3, prereqs: [], postreqs: ["CV3002", "CV2005"] },
    "CV2005": { name: "Mechanics of Solids-I", credits: 2, prereqs: ["NS1004"], postreqs: ["CV2006", "CV3007"] },
    "CV2006": { name: "Structural Analysis-I", credits: 3, prereqs: ["NS1004"], postreqs: ["CV3008", "CV2009"] },
    "CV2009": { name: "Civil Engineering Graphics and Construction", credits: 1, prereqs: ["CV1002"], postreqs: [] },
    "CV2010": { name: "Quantity and Cost Estimation", credits: 1, prereqs: [], postreqs: [] },
    "CV3001": { name: "Advanced Fluid Mechanics", credits: 3, prereqs: ["CV2002"], postreqs: [] },
    "CV3002": { name: "Reinforced Concrete Design-I", credits: 3, prereqs: ["CV2005"], postreqs: ["CV4003"] },
    "CV3006": { name: "Environmental Engineering - I", credits: 2, prereqs: ["CV2002"], postreqs: ["CV4001"] },
    "CV3007": { name: "Mechanics of Solids-II", credits: 2, prereqs: ["CV2001"], postreqs: [] },
    "CV3008": { name: "Structural Analysis-II", credits: 3, prereqs: ["CV2006"], postreqs: [] },
    "CV4001": { name: "Environmental Engineering - II", credits: 2, prereqs: ["CV3006"], postreqs: [] },
    "CV4003": { name: "Reinforced Concrete Design-II", credits: 3, prereqs: ["CV3002"], postreqs: ["CV4010"] },
    "CV4004": { name: "Transportation Planning and Engineering", credits: 3, prereqs: ["CV2001"], postreqs: [] },
    "CV4005": { name: "Steel Structures", credits: 3, prereqs: ["CV2005"], postreqs: ["CV4010"] },
    "CV4008": { name: "Fundamentals of Dynamics and its Applications", credits: 2, prereqs: ["CV2006"], postreqs: [] },
    "CV4009": { name: "Hydraulic Engineering", credits: 2, prereqs: ["CV2002"], postreqs: ["CV4011"] },
    "CV4010": { name: "Design of Structures", credits: 1, prereqs: ["CV4005", "CV3002"], postreqs: [] },
    "CV4011": { name: "Irrigation and Drainage Engineering", credits: 2, prereqs: ["CV3009"], postreqs: [] },
    "CV4091": { name: "Final Year Design Project - I", credits: 0, prereqs: [], postreqs: ["CV4092"] },
    "CV4092": { name: "Final Year Design Project - II", credits: 0, prereqs: ["CV4091"], postreqs: [] }
  },
  "BBA": {
    "AF1001": { name: "Fundamentals of Accounting", credits: 3, prereqs: [], postreqs: ["AF1002"] },
    "AF1002": { name: "Financial Accounting", credits: 3, prereqs: ["AF1001"], postreqs: ["AF2003", "AF2004", "AF3001"] },
    "MT1002": { name: "Business Math - I", credits: 3, prereqs: [], postreqs: ["MT2004"] },
    "MT2004": { name: "Business Math - II", credits: 3, prereqs: ["MT1002"], postreqs: ["MG3003"] },
    "MG1001": { name: "Fundamentals of Management", credits: 3, prereqs: [], postreqs: ["MG2001", "MG3004"] },
    "MG1002": { name: "Marketing Management", credits: 3, prereqs: [], postreqs: ["MG2003", "MG3038"] },
    "SS1016": { name: "English - I", credits: 2, prereqs: [], postreqs: ["SS1006"] },
    "SS1006": { name: "English - II", credits: 3, prereqs: ["SS1016"], postreqs: [] },
    "CS1001": { name: "IT in Business", credits: 2, prereqs: [], postreqs: [] },
    "MG2001": { name: "Organizational Behaviour", credits: 3, prereqs: ["MG1001"], postreqs: [] },
    "MG2003": { name: "Consumer Behaviour", credits: 3, prereqs: ["MG1002"], postreqs: [] },
    "MG2008": { name: "Data Analysis for Business I", credits: 3, prereqs: [], postreqs: ["MG2009"] },
    "MG2009": { name: "Data Analysis for Business II", credits: 3, prereqs: ["MG2008"], postreqs: [] },
    "MG2010": { name: "Business Communication", credits: 3, prereqs: [], postreqs: ["MG3014"] },
    "AF2003": { name: "Management Accounting", credits: 3, prereqs: ["AF1002"], postreqs: [] },
    "AF2004": { name: "Business Finance", credits: 3, prereqs: ["AF1002", "MT1002"], postreqs: ["AF3001"] },
    "MG3003": { name: "Basic Econometrics", credits: 3, prereqs: ["MG2009"], postreqs: [] },
    "MG3004": { name: "Human Resource Management", credits: 3, prereqs: ["MG1001"], postreqs: [] },
    "MG3006": { name: "Operations Management", credits: 3, prereqs: ["MT1002"], postreqs: [] },
    "MG3014": { name: "Advanced Business Communication", credits: 3, prereqs: ["MG2010"], postreqs: [] },
    "CS3003": { name: "Management Information Systems", credits: 3, prereqs: ["CS1001"], postreqs: [] },
    "AF3001": { name: "Financial Management", credits: 3, prereqs: ["AF2004"], postreqs: [] },
    "MG3038": { name: "Digital Media Marketing", credits: 3, prereqs: ["MG1002"], postreqs: [] },
    "BA2006": { name: "Fundamentals of Business Analytics", credits: 3, prereqs: ["MG2009", "CS2016"], postreqs: [] },
    "MG3010": { name: "Methods in Business Research", credits: 3, prereqs: [], postreqs: [] },
    "MG4003": { name: "Strategic Management", credits: 3, prereqs: ["MG1001"], postreqs: [] },
    "MG4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["MG4092"] },
    "MG4092": { name: "Final Year Project - II", credits: 0, prereqs: ["MG4091"], postreqs: [] }
  },
  "AF": {
    "CS1001": { name: "IT in Business", credits: 2, prereqs: [], postreqs: [] },
    "AF1001": { name: "Fundamentals of Accounting", credits: 3, prereqs: [], postreqs: ["AF1002"] },
    "AF1002": { name: "Financial Accounting", credits: 3, prereqs: ["AF1001"], postreqs: ["AF2001", "AF2003", "AF2004", "AF3002", "AF4006"] },
    "MT1002": { name: "Business Math - I", credits: 3, prereqs: [], postreqs: ["MT2004"] },
    "MT2004": { name: "Business Math - II", credits: 3, prereqs: ["MT1002"], postreqs: ["MG3003"] },
    "MG1002": { name: "Marketing Management", credits: 3, prereqs: [], postreqs: [] },
    "SS1016": { name: "English - I", credits: 2, prereqs: [], postreqs: ["SS1006"] },
    "SS1006": { name: "English - II", credits: 3, prereqs: ["SS1016"], postreqs: [] },
    "MG2008": { name: "Data Analysis for Business - I", credits: 3, prereqs: [], postreqs: ["MG2009"] },
    "MG2009": { name: "Data Analysis for Business - II", credits: 3, prereqs: ["MG2008"], postreqs: ["MG3003"] },
    "AF2001": { name: "Corporate Accounting - I", credits: 3, prereqs: ["AF1002"], postreqs: ["AF2002"] },
    "AF2002": { name: "Corporate Accounting - II", credits: 3, prereqs: ["AF2001"], postreqs: [] },
    "AF2003": { name: "Management Accounting", credits: 3, prereqs: ["AF1002"], postreqs: [] },
    "AF2004": { name: "Business Finance", credits: 3, prereqs: ["AF1002", "MT1002"], postreqs: ["AF3001", "AF3002"] },
    "AF2005": { name: "Cost and Management Accounting", credits: 3, prereqs: ["AF1002"], postreqs: [] },
    "MG3003": { name: "Basic Econometrics", credits: 3, prereqs: ["MG2009"], postreqs: [] },
    "AF3001": { name: "Financial Management", credits: 3, prereqs: ["AF2004"], postreqs: ["AF4006", "MG4527"] },
    "AF3002": { name: "Financial Statement Analysis", credits: 3, prereqs: ["AF1002"], postreqs: [] },
    "AF3004": { name: "Accounting for Decision Making", credits: 3, prereqs: ["AF2005"], postreqs: [] },
    "AF4005": { name: "Audit and Assurance", credits: 3, prereqs: ["AF1002"], postreqs: [] },
    "AF4006": { name: "Investment Analysis and Management", credits: 3, prereqs: ["AF3001"], postreqs: [] },
    "AF4007": { name: "Financial Risk Management", credits: 3, prereqs: ["AF3001"], postreqs: [] },
    "MG4527": { name: "Portfolio Management", credits: 3, prereqs: [], postreqs: [] },
    "AF4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["AF4092"] },
    "AF4092": { name: "Final Year Project - II", credits: 0, prereqs: ["AF4091"], postreqs: [] }
  },
  "BA": {
    "CS1001": { name: "IT in Business", credits: 2, prereqs: [], postreqs: ["CS2016"] },
    "AF1001": { name: "Fundamentals of Accounting", credits: 3, prereqs: [], postreqs: ["AF1002"] },
    "AF1002": { name: "Financial Accounting", credits: 3, prereqs: ["AF1001"], postreqs: ["AF2004"] },
    "MT1002": { name: "Business Math - I", credits: 3, prereqs: [], postreqs: ["MT2004"] },
    "MT2004": { name: "Business Math - II", credits: 3, prereqs: ["MT1002"], postreqs: ["MG3003"] },
    "MG1001": { name: "Fundamentals of Management", credits: 3, prereqs: [], postreqs: ["MG3004"] },
    "MG1002": { name: "Marketing Management", credits: 3, prereqs: [], postreqs: ["MG2003"] },
    "SS1016": { name: "English - I", credits: 2, prereqs: [], postreqs: ["SS1006"] },
    "SS1006": { name: "English - II", credits: 3, prereqs: ["SS1016"], postreqs: [] },
    "MG2008": { name: "Data Analysis for Business I", credits: 3, prereqs: [], postreqs: ["MG2009"] },
    "MG2009": { name: "Data Analysis for Business II", credits: 3, prereqs: ["MG2008"], postreqs: ["BA2006", "MG3003"] },
    "CS2016": { name: "Programming for Business", credits: 3, prereqs: [], postreqs: ["BA2006", "CS2003"] },
    "AF2004": { name: "Business Finance", credits: 3, prereqs: ["AF1002", "MT1002"], postreqs: ["AF3001"] },
    "MG2003": { name: "Consumer Behaviour", credits: 3, prereqs: ["MG1002"], postreqs: [] },
    "BA2006": { name: "Fundamentals of Business Analytics", credits: 3, prereqs: ["MG2009", "CS2016"], postreqs: ["BA3001", "BA4001"] },
    "MG3003": { name: "Basic Econometrics", credits: 3, prereqs: ["MG2009"], postreqs: [] },
    "MG3004": { name: "Human Resource Management", credits: 3, prereqs: ["MG1001"], postreqs: [] },
    "AF3001": { name: "Financial Management", credits: 3, prereqs: ["AF2004"], postreqs: [] },
    "CS2003": { name: "Data Structures and Business Application", credits: 3, prereqs: ["CS2016"], postreqs: [] },
    "BA3001": { name: "Machine Learning for Business Analytics", credits: 3, prereqs: ["CS2003"], postreqs: [] },
    "BA3002": { name: "Business Data and Text Mining", credits: 3, prereqs: ["CS2003"], postreqs: [] },
    "BA3004": { name: "Database Systems for Business", credits: 3, prereqs: ["CS2016"], postreqs: [] },
    "BA4001": { name: "Decision Science for Business", credits: 3, prereqs: ["BA2006"], postreqs: [] },
    "BA4002": { name: "Predictive Analytics", credits: 3, prereqs: [], postreqs: [] },
    "BA4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["BA4092"] },
    "BA4092": { name: "Final Year Project - II", credits: 0, prereqs: ["BA4091"], postreqs: [] }
  },
  "FT": {
    "CS1001": { name: "IT in Business", credits: 2, prereqs: [], postreqs: ["CS2016"] },
    "AF1001": { name: "Fundamentals of Accounting", credits: 3, prereqs: [], postreqs: ["AF1002"] },
    "AF1002": { name: "Financial Accounting", credits: 3, prereqs: ["AF1001"], postreqs: ["AF2004"] },
    "MT1002": { name: "Business Math - I", credits: 3, prereqs: [], postreqs: ["MT2004"] },
    "MT2004": { name: "Business Math - II", credits: 3, prereqs: ["MT1002"], postreqs: ["MG3003"] },
    "MG1002": { name: "Marketing Management", credits: 3, prereqs: [], postreqs: [] },
    "SS1016": { name: "English - I", credits: 2, prereqs: [], postreqs: ["SS1006"] },
    "SS1006": { name: "English - II", credits: 3, prereqs: ["SS1016"], postreqs: [] },
    "MG2008": { name: "Data Analysis for Business - I", credits: 3, prereqs: [], postreqs: ["MG2009"] },
    "MG2009": { name: "Data Analysis for Business - II", credits: 3, prereqs: ["MG2008"], postreqs: ["MG3003"] },
    "CS2016": { name: "Programming for Business", credits: 3, prereqs: [], postreqs: ["CS2012", "CS3010"] },
    "CS2012": { name: "Introduction to Object Oriented Programming", credits: 3, prereqs: ["CS2016"], postreqs: ["CS2013"] },
    "AF2004": { name: "Business Finance", credits: 3, prereqs: ["AF1002", "MT1002"], postreqs: ["AF3001", "AF3009"] },
    "MG3003": { name: "Basic Econometrics", credits: 3, prereqs: ["MG2009"], postreqs: [] },
    "AF3001": { name: "Financial Management", credits: 3, prereqs: ["AF2004"], postreqs: ["AF4011", "AF4012"] },
    "AF3009": { name: "Banking and Financial Systems", credits: 3, prereqs: [], postreqs: ["AF3010"] },
    "MG3012": { name: "Blockchain Technology for Business", credits: 3, prereqs: [], postreqs: [] },
    "CS2013": { name: "Introduction to Database Systems", credits: 3, prereqs: ["CS2012"], postreqs: [] },
    "CS3010": { name: "Web Programming", credits: 3, prereqs: ["CS2016"], postreqs: [] },
    "AF3010": { name: "Banking Instruments and Procedures", credits: 3, prereqs: ["AF3009"], postreqs: [] },
    "AF3008": { name: "Business Research and Data Mining", credits: 3, prereqs: [], postreqs: [] },
    "CS3017": { name: "Enterprise Systems and Applications", credits: 3, prereqs: [], postreqs: [] },
    "AF4011": { name: "Investment and Portfolio Analytics", credits: 3, prereqs: ["AF3001"], postreqs: [] },
    "AF4012": { name: "Financial Risk Analytics and Derivatives", credits: 3, prereqs: ["AF3001"], postreqs: [] },
    "AF4013": { name: "Artificial Intelligence in Business Decision", credits: 3, prereqs: [], postreqs: [] },
    "MG4091": { name: "Final Year Project - I", credits: 0, prereqs: [], postreqs: ["MG4092"] },
    "MG4092": { name: "Final Year Project - II", credits: 0, prereqs: ["MG4091"], postreqs: [] }
  }
};

function getAllCoursesList(department) {
  const deptData = PREREQUISITES[department] || {};
  return Object.keys(deptData).map(code => ({
    code: code,
    name: deptData[code].name,
    credits: deptData[code].credits
  }));
}

function getPrerequisites(department, courseCode) {
  const deptData = PREREQUISITES[department];
  if (!deptData || !deptData[courseCode]) return { prereqs: [], postreqs: [] };
  
  const course = deptData[courseCode];
  const prereqs = course.prereqs.map(code => ({
    code: code,
    name: deptData[code]?.name || code
  }));
  const postreqs = course.postreqs.map(code => ({
    code: code,
    name: deptData[code]?.name || code
  }));
  
  return { prereqs, postreqs };
}

function searchCourse(department, query) {
  const deptData = PREREQUISITES[department] || {};
  const results = [];
  const lowerQuery = query.toLowerCase();
  
  for (const [code, data] of Object.entries(deptData)) {
    if (code.toLowerCase().includes(lowerQuery) || 
        data.name.toLowerCase().includes(lowerQuery)) {
      results.push({
        code: code,
        name: data.name,
        credits: data.credits
      });
    }
  }
  
  return results.slice(0, 10);
}

